# Ensure all peer dependencies are explicitly installed.
# See https://pnpm.io/settings#autoinstallpeers
autoInstallPeers: false

# Allows app to use workspace packages with their expected peer dependencies.
# See https://pnpm.io/settings#injectworkspacepackages
injectWorkspacePackages: true

packages:
  - apps/*
  - libs/*
  - scripts

# See https://pnpm.io/catalogs#catalogmode
catalogMode: prefer

# See https://pnpm.io/catalogs#cleanupunusedcatalogs
cleanupUnusedCatalogs: true

catalog:
  "@conform-to/react": ^1.2.2
  "@conform-to/zod": ^1.2.2
  "@epic-web/cachified": ^5.2.0
  "@faker-js/faker": ^8.0.2
  "@mjackson/form-data-parser": ^0.4.0
  "@mjackson/lazy-file": ^3.2.0
  "@opentelemetry/api": ^1.9.0
  "@opentelemetry/core": ^1.27.0
  "@opentelemetry/instrumentation": ^0.54.2
  "@opentelemetry/sdk-trace-base": ^1.27.0
  "@opentelemetry/semantic-conventions": ^1.27.0
  "@prisma/adapter-pg": ^6.18.0
  "@prisma/client": ^6.18.0
  "@radix-ui/react-collapsible": ^1.0.3
  "@radix-ui/react-dialog": ^1.0.4
  "@radix-ui/react-dropdown-menu": ^2.0.5
  "@radix-ui/react-navigation-menu": ^1.1.3
  "@radix-ui/react-popover": ^1.0.6
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-visually-hidden": ^1.0.3
  "@react-email/components": ^0.0.28
  "@react-email/render": ^1.0.2
  "@remix-run/dev": ~2.9.2
  "@remix-run/eslint-config": ~2.9.2
  "@remix-run/express": ~2.9.2
  "@remix-run/node": ~2.9.2
  "@remix-run/react": ~2.9.2
  "@remix-run/serve": ~2.9.2
  "@sentry/remix": ^8.37.1
  "@tailwindcss/container-queries": ^0.1.1
  "@total-typescript/ts-reset": ^0.5.1
  "@types/autosize": ^4.0.1
  "@types/body-scroll-lock": ^3.1.0
  "@types/compression": ^1.7.0
  "@types/cookie-signature": ^1.1.0
  "@types/d3-dsv": ^3.0.2
  "@types/express": ^4.17.9
  "@types/lodash.chunk": ^4.2.7
  "@types/lodash.difference": ^4.5.7
  "@types/lodash.groupby": ^4.6.9
  "@types/lodash.intersection": ^4.4.7
  "@types/lodash.isequal": ^4.5.6
  "@types/lodash.merge": ^4.6.9
  "@types/lodash.orderby": ^4.6.7
  "@types/lodash.pick": ^4.4.9
  "@types/luxon": ^3.3.1
  "@types/morgan": ^1.9.2
  "@types/node": ^22.8.7
  "@types/pg": ^8.10.2
  "@types/pg-copy-streams": ^1.2.2
  "@types/react": ^18.2.21
  "@types/react-dom": ^18.2.7
  "@types/react-transition-group": ^4.4.6
  "@types/source-map-support": ^0.5.6
  "@types/uuid": ^9.0.2
  "@unpic/pixels": ^1.2.0
  "@unpic/placeholder": ^0.1.2
  autoprefixer: ^10.4.15
  autosize: ^6.0.1
  blurhash: ^2.0.5
  body-scroll-lock: ^3.1.5
  bowser: ^2.11.0
  chokidar: ^3.5.3
  chokidar-cli: ^3.0.0
  cloudinary: ^2.2.0
  compression: ^1.7.4
  cookie-signature: ^1.2.1
  croner: ^8.0.0
  d3-dsv: ^3.0.1
  dotenv-flow: ^4.1.0
  downshift: ^9.0.6
  encoding: ^0.1.13
  eslint: ^8.56.0
  eslint-config-prettier: ^9.1.0
  express: ^4.17.1
  focus-trap: ^7.5.2
  get-port: ^5.1.1
  googleapis: ^144.0.0
  history: ^5.3.0
  isbot: ^5.1.8
  lodash.chunk: ^4.2.0
  lodash.difference: ^4.5.0
  lodash.groupby: ^4.6.0
  lodash.intersection: ^4.4.0
  lodash.isequal: ^4.5.0
  lodash.merge: ^4.6.2
  lodash.orderby: ^4.6.0
  lodash.pick: ^4.4.0
  lru-cache: ^10.0.1
  luxon: ^3.4.2
  metascraper: ^5.36.0
  metascraper-date: ^5.36.0
  metascraper-image: ^5.36.0
  metascraper-publisher: ^5.36.0
  metascraper-title: ^5.36.0
  morgan: ^1.10.0
  msw: ^2.3.1
  node-html-parser: ^6.1.12
  npm-run-all: ^4.1.5
  pg: ^8.11.3
  pg-copy-streams: ^6.0.6
  pm2: ^5.3.0
  prettier: ^3.2.4
  prettier-plugin-organize-imports: ^3.2.4
  prettier-plugin-tailwindcss: ^0.6.1
  prisma: ^6.18.0
  react: ^18.2.0
  react-dnd: ^16.0.1
  react-dnd-html5-backend: ^16.0.1
  react-dnd-touch-backend: ^16.0.1
  react-dom: ^18.2.0
  react-markdown: ^9.0.1
  react-router: ^6.23.1
  react-transition-group: ^4.4.5
  remark-breaks: ^4.0.0
  remark-gfm: ^4.0.0
  remix-utils: ^7.5.0
  resend: ^4.0.1-alpha.0
  scroll-into-view-if-needed: ^3.1.0
  source-map-support: ^0.5.21
  tailwindcss: ^3.3.3
  tiny-invariant: ^1.3.1
  tsc-alias: ^1.8.16
  tsx: ^4.7.0
  type-fest: ^4.3.1
  typescript: ~5.4.5
  uuid: ^9.0.0
  vite: ^5.2.12
  vite-tsconfig-paths: ^4.3.2
  zod: ^3.22.2
  zod-form-data: ^2.0.1
