# Allows app to use workspace packages with their expected peer dependencies.
# See https://pnpm.io/settings#injectworkspacepackages
injectWorkspacePackages: true

packages:
  - apps/*
  - libs/*
  - scripts
