http:
  routers:
    website:
      rule: "Host(`animeaux.localhost`)"
      service: service-website

    website-remix:
      rule: "Host(`remix.animeaux.localhost`)"
      service: service-website-remix

    faune:
      rule: "Host(`faune.animeaux.localhost`)"
      service: service-faune

    api:
      rule: "Host(`api.animeaux.localhost`)"
      service: service-api

  services:
    service-website:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

    service-website-remix:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3002"

    service-faune:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

    service-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4000"
