http:
  routers:
    website:
      rule: "Host(`animeaux.localhost`)"
      service: service-website

    show:
      rule: "Host(`show.animeaux.localhost`)"
      service: service-show

    admin:
      rule: "Host(`admin.animeaux.localhost`)"
      service: service-admin

  services:
    service-website:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

    service-show:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

    service-admin:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3002"
