http:
  routers:
    website:
      rule: "Host(`animeaux.localhost`)"
      service: service-website

    show:
      rule: "Host(`show.animeaux.localhost`)"
      service: service-show

    faune:
      rule: "Host(`faune.animeaux.localhost`)"
      service: service-faune

    api:
      rule: "Host(`api.animeaux.localhost`)"
      service: service-api

  services:
    service-website:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

    service-show:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3003"

    service-faune:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

    service-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:4000"
