import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import {
  formatBreakpoints,
  formatSpacing,
  relativeToCwd,
  safelyReadFile,
} from "@animeaux/dev-tools"
import { __unstable__loadDesignSystem as loadDesignSystem } from "@tailwindcss/node"
import { formatHex } from "culori"
import type { __unstable__loadDesignSystem as loadDesignSystemBase } from "tailwindcss"
import invariant from "tiny-invariant"

const FILENAME = fileURLToPath(import.meta.url)
const DIRNAME = dirname(FILENAME)
const SCRIPT_NAME = relativeToCwd(FILENAME)
const STYLES_DIRECTORY = resolve(DIRNAME, "../src/styles")
const MAIN_STYLE_FILE = resolve(STYLES_DIRECTORY, "main.css")
const TEXT_STYLE_FILE = resolve(STYLES_DIRECTORY, "text-style.css")
const DEST_DIRECTORY = resolve(DIRNAME, "../src/generated")
const DEST_FILE = resolve(DEST_DIRECTORY, "theme.ts")

console.log("Building...")

const [mainCss, textStyleCss] = await Promise.all([
  readFile(MAIN_STYLE_FILE, "utf-8"),
  readFile(TEXT_STYLE_FILE, "utf-8"),
])

// The type cast is required because @tailwindcss/node's `loadDesignSystem`
// types are broken (`design.theme: any`). We use tailwindcss's
// `loadDesignSystem` types because it's used internally and its types are fine.
const design = (await loadDesignSystem(mainCss, {
  base: STYLES_DIRECTORY,
})) as Awaited<ReturnType<typeof loadDesignSystemBase>>

// Ensure the destination directory exists.
await mkdir(DEST_DIRECTORY, { recursive: true })

const content = `// This file is generated by ${SCRIPT_NAME}
${formatBreakpoints(design.theme.namespace("--breakpoint"))}

${getFonts()}

${getColors()}

${formatSpacing(design.theme.namespace("--spacing"))}
`

const currentContent = await safelyReadFile(DEST_FILE)
if (currentContent === content) {
  console.info(`Theme didn't change (${relativeToCwd(DEST_FILE)})`)

  // The theme will not change so we don't re-generate it to avoid triggering
  // a re-build of remix.
  process.exit(0)
}

await writeFile(DEST_FILE, content)
console.info(`Built theme (${relativeToCwd(DEST_FILE)})`)

function getColors() {
  const colors = design.theme.namespace("--color")

  const alabaster = colors.get("alabaster-100")
  const mystic = colors.get("mystic-500")
  const prussianBlue = colors.get("prussian-blue-950")
  const white = colors.get("white")

  return `export namespace Color {
  export const alabaster = ${JSON.stringify(alabaster)}
  export const alabasterHex = ${JSON.stringify(formatHex(alabaster))}
  export const mystic = ${JSON.stringify(mystic)}
  export const mysticHex = ${JSON.stringify(formatHex(mystic))}
  export const prussianBlue = ${JSON.stringify(prussianBlue)}
  export const prussianBlueHex = ${JSON.stringify(formatHex(prussianBlue))}
  export const white = ${JSON.stringify(white)}
  export const whiteHex = ${JSON.stringify(formatHex(white))}
  export const primary = Color.mystic
  export const primaryHex = Color.mysticHex
}`
}

function getFonts() {
  const fontFaces = parseFontFaces()

  const fonts = design.theme.namespace("--font")
  const sans = parseFontFamily("sans", fonts, fontFaces)
  const serif = parseFontFamily("serif", fonts, fontFaces)

  return `export namespace Font {
  export const sans = ${JSON.stringify(sans, null, 2)} as const

  export const serif = ${JSON.stringify(serif, null, 2)} as const

  export const all = [sans, serif]
}`
}

type FontVariant = {
  style: string
  weight: number
  url: string
  format: string
}

function parseFontFaces() {
  const variantsByFamily = new Map<string, FontVariant[]>()

  for (const match of textStyleCss.matchAll(
    /@font-face\s*\{(?<content>[^}]+)\}/g,
  )) {
    const content = match.groups?.content?.trim()

    invariant(content, "Empty @font-face in theme")

    const { familyName, variant } = parseFontFace(content)

    const variants = variantsByFamily.get(familyName) ?? []
    variants.push(variant)
    variantsByFamily.set(familyName, variants)
  }

  invariant(variantsByFamily.size > 0, "No @font-face found in theme")

  return variantsByFamily
}

function parseFontFace(content: string) {
  const familyName = parseFontProperty(content, /font-family:\s*["]([^"]+)["]/)
  const style = parseFontProperty(content, /font-style:\s*(\w+)/)
  const weight = Number(parseFontProperty(content, /font-weight:\s*(\d+)/))
  const url = parseFontProperty(content, /url\(["]([^")]+)["]\)/)
  const format = parseFontProperty(content, /format\(["]([^")]+)["]\)/)

  const variant: FontVariant = { style, weight, url, format }

  return { familyName, variant }
}

function parseFontProperty(content: string, regExp: RegExp) {
  const match = content.match(regExp)
  const value = match?.[1]?.trim()

  invariant(value, `Unsupported @font-face from theme:\n${content}\n`)

  return value
}

function parseFontFamily(
  familyType: string,
  themeFonts: Map<string | null, string>,
  fontFaces: Map<string, FontVariant[]>,
) {
  const content = themeFonts.get(familyType)

  invariant(
    content != null,
    `A \`--font-${familyType}\` definition is missing in the theme`,
  )

  const [name, ...fallbacks] = content
    .split(",")
    .map((name) => name.trim().replaceAll(/(^"|"$)/g, ""))

  invariant(
    name != null && fallbacks.length > 0,
    `Invalid \`--font-${familyType}\` definition in the theme`,
  )

  const variants = fontFaces.get(name)

  invariant(
    variants != null && variants.length > 0,
    `No variant found for font family "${name}"`,
  )

  return { name, fallbacks, variants }
}
