import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { __unstable__loadDesignSystem as loadDesignSystem } from "@tailwindcss/node"
import { formatHex } from "culori"
import { orderBy } from "es-toolkit/array"
import type { __unstable__loadDesignSystem as loadDesignSystemBase } from "tailwindcss"
import invariant from "tiny-invariant"

import { relativeToCwd, safelyReadFile } from "./shared.js"

const FILENAME = fileURLToPath(import.meta.url)
const DIRNAME = dirname(FILENAME)
const SCRIPT_NAME = relativeToCwd(FILENAME)
const STYLES_DIRECTORY = resolve(DIRNAME, "../src/styles")
const MAIN_STYLE_FILE = resolve(STYLES_DIRECTORY, "main.css")
const TEXT_STYLE_FILE = resolve(STYLES_DIRECTORY, "text-style.css")
const DEST_DIRECTORY = resolve(DIRNAME, "../src/generated")
const DEST_FILE = resolve(DEST_DIRECTORY, "theme.ts")

console.log("Building...")

const [mainCss, textStyleCss] = await Promise.all([
  readFile(MAIN_STYLE_FILE, "utf-8"),
  readFile(TEXT_STYLE_FILE, "utf-8"),
])

// The type cast is required because @tailwindcss/node's `loadDesignSystem`
// types are broken (`design.theme: any`). We use tailwindcss's
// `loadDesignSystem` types because it's used internally and its types are fine.
const design = (await loadDesignSystem(mainCss, {
  base: STYLES_DIRECTORY,
})) as Awaited<ReturnType<typeof loadDesignSystemBase>>

// Ensure the destination directory exists.
await mkdir(DEST_DIRECTORY, { recursive: true })

const content = `// This file is generated by ${SCRIPT_NAME}
${getBreakpoints()}

${getFonts()}

${getColors()}

${getSpacing()}
`

const currentContent = await safelyReadFile(DEST_FILE)
if (currentContent === content) {
  console.info(`Theme didn't change (${relativeToCwd(DEST_FILE)})`)

  // The theme will not change so we don't re-generate it to avoid triggering
  // a re-build of remix.
  process.exit(0)
}

await writeFile(DEST_FILE, content)
console.info(`Built theme (${relativeToCwd(DEST_FILE)})`)

function getBreakpoints() {
  const breakpoints = design.theme.namespace("--breakpoint")

  const sortedEntries = orderBy(
    Array.from(breakpoints.entries())
      // `null` is used as key for a property with the namespace's name (e.g.
      // `--breakpoint: <value>`).
      // For breakpoints this shouldn't happen.
      .filter((entry): entry is [string, string] => entry[0] != null)
      .map(
        ([breakpoint, length]) =>
          [breakpoint, getLengthValuePx(length)] as const,
      ),
    [([_breakpoint, valuePx]) => valuePx],
    ["desc"],
  )

  return `export type Breakpoint = typeof Breakpoint.names[number]

export namespace Breakpoint {
  /** Breakpoint names sorted by descending value. */
  export const names = ${JSON.stringify(
    sortedEntries.map(([breakpoint]) => breakpoint),
  )} as const

  /** Breakpoint values in pixels. */
  export const value = ${JSON.stringify(Object.fromEntries(sortedEntries), null, 2)} as const
}`
}

function getColors() {
  const colors = design.theme.namespace("--color")

  const alabaster = colors.get("alabaster-100")
  const mystic = colors.get("mystic-500")
  const prussianBlue = colors.get("prussian-blue-950")
  const white = colors.get("white")

  return `export namespace Color {
  export const alabaster = ${JSON.stringify(alabaster)}
  export const alabasterHex = ${JSON.stringify(formatHex(alabaster))}
  export const mystic = ${JSON.stringify(mystic)}
  export const mysticHex = ${JSON.stringify(formatHex(mystic))}
  export const prussianBlue = ${JSON.stringify(prussianBlue)}
  export const prussianBlueHex = ${JSON.stringify(formatHex(prussianBlue))}
  export const white = ${JSON.stringify(white)}
  export const whiteHex = ${JSON.stringify(formatHex(white))}
  export const primary = Color.mystic
  export const primaryHex = Color.mysticHex
}`
}

function getFonts() {
  const fontFaces = parseFontFaces()

  const fonts = design.theme.namespace("--font")
  const sans = parseFontFamily("sans", fonts, fontFaces)
  const serif = parseFontFamily("serif", fonts, fontFaces)

  return `export namespace Font {
  export const sans = ${JSON.stringify(sans, null, 2)} as const

  export const serif = ${JSON.stringify(serif, null, 2)} as const
  
  export const all = [sans, serif]
}`
}

type FontVariant = {
  style: string
  weight: number
  url: string
  format: string
}

function parseFontFaces() {
  const variantsByFamily = new Map<string, FontVariant[]>()

  for (const match of textStyleCss.matchAll(
    /@font-face\s*\{(?<content>[^}]+)\}/g,
  )) {
    const content = match.groups?.content?.trim()

    invariant(content, "Empty @font-face in theme")

    const { familyName, variant } = parseFontFace(content)

    const variants = variantsByFamily.get(familyName) ?? []
    variants.push(variant)
    variantsByFamily.set(familyName, variants)
  }

  invariant(variantsByFamily.size > 0, "No @font-face found in theme")

  return variantsByFamily
}

function parseFontFace(content: string) {
  const familyName = parseFontProperty(content, /font-family:\s*["]([^"]+)["]/)
  const style = parseFontProperty(content, /font-style:\s*(\w+)/)
  const weight = Number(parseFontProperty(content, /font-weight:\s*(\d+)/))
  const url = parseFontProperty(content, /url\(["]([^")]+)["]\)/)
  const format = parseFontProperty(content, /format\(["]([^")]+)["]\)/)

  const variant: FontVariant = { style, weight, url, format }

  return { familyName, variant }
}

function parseFontProperty(content: string, regExp: RegExp) {
  const match = content.match(regExp)
  const value = match?.[1]?.trim()

  invariant(value, `Unsupported @font-face from theme:\n${content}\n`)

  return value
}

function parseFontFamily(
  familyType: string,
  themeFonts: Map<string | null, string>,
  fontFaces: Map<string, FontVariant[]>,
) {
  const content = themeFonts.get(familyType)

  invariant(
    content != null,
    `A \`--font-${familyType}\` definition is missing in the theme`,
  )

  const [name, ...fallbacks] = content
    .split(",")
    .map((name) => name.trim().replaceAll(/(^"|"$)/g, ""))

  invariant(
    name != null && fallbacks.length > 0,
    `Invalid \`--font-${familyType}\` definition in the theme`,
  )

  const variants = fontFaces.get(name)

  invariant(
    variants != null && variants.length > 0,
    `No variant found for font family "${name}"`,
  )

  return { name, fallbacks, variants }
}

function getSpacing() {
  const spacings = design.theme.namespace("--spacing")

  // A property with the namespace's name has `null` as key. (e.g.
  // `--spacing: <value>`).
  const spacing = spacings.get(null)

  invariant(spacing != null, "A `--spacing` definition is missing in the theme")

  return `export namespace Spacing {
  export const unitPx = ${getLengthValuePx(spacing)}
}`
}

/**
 * Returns the given CSS length in pixels.
 *
 * @param length expressed with the `<length>` CSS type.
 * @returns The value in pixels
 * @see https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/length
 */
function getLengthValuePx(length: string) {
  length = length.trim()

  /**
   * Matches values for the `<length>` CSS type.
   * We only support unitless `0`, rem and px.
   *
   * @see https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/length
   */
  const CSS_LENGTH_REGEXP = /(?<value>-?\d*\.?\d+)(?<unit>.*)/

  const match = length.match(CSS_LENGTH_REGEXP)

  invariant(
    match?.groups?.value != null,
    `Invalid CSS length from theme: "${length}"`,
  )

  const value = Number(match.groups.value)

  // The unit is optional when the value is `0`.
  // See https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/length#syntax
  const unit = match.groups.unit || "px"

  switch (unit) {
    case "px": {
      return value
    }

    case "rem": {
      return 16 * value
    }

    default: {
      throw new Error(`Unsupported length unit: "${unit}" in "${length}"`)
    }
  }
}
