import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import {
  formatBreakpoints,
  formatSpacing,
  relativeToCwd,
  safelyReadFile,
} from "@animeaux/dev-tools"
import { __unstable__loadDesignSystem as loadDesignSystem } from "@tailwindcss/node"
import type { __unstable__loadDesignSystem as loadDesignSystemBase } from "tailwindcss"

const FILENAME = fileURLToPath(import.meta.url)
const DIRNAME = dirname(FILENAME)
const SCRIPT_NAME = relativeToCwd(FILENAME)
const STYLES_DIRECTORY = resolve(DIRNAME, "../src/styles")
const MAIN_STYLE_FILE = resolve(STYLES_DIRECTORY, "main.css")
const DEST_DIRECTORY = resolve(DIRNAME, "../src/generated")
const DEST_FILE = resolve(DEST_DIRECTORY, "theme.ts")

console.log("Building...")

const mainCss = await readFile(MAIN_STYLE_FILE, "utf-8")

// The type cast is required because @tailwindcss/node's `loadDesignSystem`
// types are broken (`design.theme: any`). We use tailwindcss's
// `loadDesignSystem` types because it's used internally and its types are fine.
const design = (await loadDesignSystem(mainCss, {
  base: STYLES_DIRECTORY,
})) as Awaited<ReturnType<typeof loadDesignSystemBase>>

// Ensure the destination directory exists.
await mkdir(DEST_DIRECTORY, { recursive: true })

const content = `// This file is generated by ${SCRIPT_NAME}
${formatBreakpoints(design.theme.namespace("--breakpoint"))}

${getColors()}

${formatSpacing(design.theme.namespace("--spacing"))}
`

const currentContent = await safelyReadFile(DEST_FILE)
if (currentContent === content) {
  console.info(`Theme didn't change (${relativeToCwd(DEST_FILE)})`)

  // The theme will not change so we don't re-generate it to avoid triggering
  // a re-build of remix.
  process.exit(0)
}

await writeFile(DEST_FILE, content)
console.info(`Built theme (${relativeToCwd(DEST_FILE)})`)

function getColors() {
  const colors = design.theme.namespace("--color")

  return `export namespace Color {
  export const primary = ${JSON.stringify(colors.get("blue-500"))}
  export const white = ${JSON.stringify(colors.get("white"))}
}`
}
