#! /bin/bash
set -euo pipefail

build_all ()
{
  cd shared
  printf "\n📦 Building shared\n\n"
  yarn clean-build

  cd ../api
  printf "\n📦 Building api\n\n"
  yarn clean-build

  cd ../apps/faune
  printf "\n📦 Building faune\n\n"
  yarn clean-build

  cd ../website
  printf "\n📦 Building website\n\n"
  yarn clean-build

  printf "\n✅ Build succeeded\n\n"
}


build_all
