#! /bin/bash
set -euo pipefail

build_all ()
{
  printf "\n📦 Building shared\n\n"
  yarn --cwd shared clean-build

  printf "\n📦 Building api\n\n"
  yarn --cwd api clean-build

  printf "\n📦 Building website\n\n"
  yarn --cwd apps/website clean-build

  printf "\n📦 Building faune\n\n"
  yarn --cwd apps/faune clean-build

  printf "\n✅ Build succeeded\n\n"
}


build_all
