import { defineConfig, globalIgnores } from "eslint/config"
import importX from "eslint-plugin-import-x"
import jsxA11y from "eslint-plugin-jsx-a11y"
import react from "eslint-plugin-react"
import reactHooks from "eslint-plugin-react-hooks"
import simpleImportSort from "eslint-plugin-simple-import-sort"
import unusedImports from "eslint-plugin-unused-imports"
import globals from "globals"
import typescript from "typescript-eslint"

/**
 * @see https://eslint.org/docs/latest/use/configure/rules#rule-severities
 */
export const Severity = {
  /**
   * Set this for code that causes runtime errors.
   *
   * @alias 2
   */
  ERROR: "error",

  /**
   * Set this for valid code that is undesired.
   *
   * @alias 1
   */
  WARN: "warn",

  /**
   * Set this to disable an inherited rule.
   *
   * @alias 0
   */
  OFF: "off",
}

export default defineConfig([
  // Applies to all configurations.
  //
  // https://eslint.org/docs/latest/use/configure/ignore
  globalIgnores([
    // Compiled code by Vite or tsc.
    "**/build/**",

    // Service worker generated by MSW.
    "**/public/mock-service-worker.js",

    // Compiled application entry point by tsc.
    "**/server.js",

    // Source code generated by codegen scripts.
    "**/src/generated/**",
  ]),

  {
    name: "dev-tools/global-variables",

    languageOptions: {
      // https://eslint.org/docs/latest/use/configure/language-options#predefined-global-variables
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },

  {
    name: "dev-tools/javascript",

    plugins: {
      // Add this plugin here as it splits `no-unused-vars` into
      // `unused-imports/no-unused-imports` and `unused-imports/no-unused-vars`.
      "unused-imports": unusedImports,
    },

    rules: {
      // https://eslint.org/docs/latest/rules/constructor-super
      "constructor-super": Severity.WARN,

      // https://eslint.org/docs/latest/rules/for-direction
      "for-direction": Severity.WARN,

      // https://eslint.org/docs/latest/rules/getter-return
      "getter-return": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-case-declarations
      "no-case-declarations": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-cond-assign
      "no-cond-assign": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-const-assign
      "no-const-assign": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-constant-binary-expression
      "no-constant-binary-expression": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-constant-condition
      "no-constant-condition": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-debugger
      "no-debugger": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-dupe-args
      "no-dupe-args": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-dupe-class-members
      "no-dupe-class-members": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-dupe-else-if
      "no-dupe-else-if": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-dupe-keys
      "no-dupe-keys": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-duplicate-case
      "no-duplicate-case": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-empty
      "no-empty": [
        Severity.WARN,
        {
          // Empty catch block can be use for expected errors.
          allowEmptyCatch: true,
        },
      ],

      // https://eslint.org/docs/latest/rules/no-empty-character-class
      "no-empty-character-class": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-empty-pattern
      "no-empty-pattern": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-ex-assign
      "no-ex-assign": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-extra-boolean-cast
      "no-extra-boolean-cast": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-fallthrough
      "no-fallthrough": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-func-assign
      "no-func-assign": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-global-assign
      "no-global-assign": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-import-assign
      "no-import-assign": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-invalid-regexp
      "no-invalid-regexp": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-irregular-whitespace
      "no-irregular-whitespace": [
        Severity.WARN,
        {
          // Allow in JSX text because we hard code text.
          skipJSXText: true,

          // Allow in template literals because we hard code text in them (and
          // because strings are skipped by default).
          skipTemplates: true,
        },
      ],

      // https://eslint.org/docs/latest/rules/no-new-native-nonconstructor
      "no-new-native-nonconstructor": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-octal
      "no-octal": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-prototype-builtins
      "no-prototype-builtins": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-redeclare
      "no-redeclare": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-regex-spaces
      "no-regex-spaces": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-self-assign
      "no-self-assign": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-setter-return
      "no-setter-return": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-shadow-restricted-names
      "no-shadow-restricted-names": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-sparse-arrays
      "no-sparse-arrays": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-this-before-super
      "no-this-before-super": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-undef
      "no-undef": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-unexpected-multiline
      "no-unexpected-multiline": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-unreachable
      "no-unreachable": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-unsafe-finally
      "no-unsafe-finally": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-unsafe-negation
      "no-unsafe-negation": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-unsafe-optional-chaining
      "no-unsafe-optional-chaining": Severity.ERROR,

      // https://eslint.org/docs/latest/rules/no-unused-expressions
      "no-unused-expressions": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-unused-private-class-members
      "no-unused-private-class-members": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-useless-backreference
      "no-useless-backreference": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-useless-catch
      "no-useless-catch": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-useless-escape
      "no-useless-escape": Severity.WARN,

      // Prevent cognitive overload.
      //
      // https://eslint.org/docs/latest/rules/no-useless-rename
      "no-useless-rename": Severity.WARN,

      // https://eslint.org/docs/latest/rules/no-warning-comments
      "no-warning-comments": [
        Severity.WARN,
        {
          // We use external tools to track what needs to be done.
          // Searching code to see them is not common.
          terms: ["FIXME", "TODO"],
          location: "anywhere",
        },
      ],

      // Enfore usage of object shorthand for properties to improve readability.
      //
      // Invalid:
      //   const object = { property: property }
      //
      // Valid:
      //   const object = { property }
      //
      // https://eslint.org/docs/latest/rules/object-shorthand
      "object-shorthand": [Severity.WARN, "properties"],

      // https://eslint.org/docs/latest/rules/prefer-const
      "prefer-const": [
        Severity.WARN,
        {
          // Allow `let` when at least one variables in destructuring is
          // reassigned.
          //
          // Example:
          //   let { a, b } = object
          //   a = a + 1
          destructuring: "all",
        },
      ],

      // https://eslint.org/docs/latest/rules/require-yield
      "require-yield": Severity.WARN,

      // https://eslint.org/docs/latest/rules/use-isnan
      "use-isnan": Severity.WARN,

      // https://eslint.org/docs/latest/rules/valid-typeof
      "valid-typeof": Severity.WARN,

      // https://github.com/sweepline/eslint-plugin-unused-imports
      "unused-imports/no-unused-imports": Severity.WARN,

      // Same options as `no-unused-vars`.
      //
      // https://github.com/sweepline/eslint-plugin-unused-imports
      // https://eslint.org/docs/latest/rules/no-unused-vars
      "unused-imports/no-unused-vars": [
        Severity.WARN,
        {
          args: "all",

          // Allow destructuring syntax to _remove_ a property.
          ignoreRestSiblings: true,

          // Use the same prefix as TypeScript's `noUnusedLocals` and
          // `noUnusedParameters`
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
    },
  },

  {
    name: "dev-tools/javascript-import-order",

    plugins: {
      import: importX,
      "simple-import-sort": simpleImportSort,
    },

    rules: {
      // https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/newline-after-import.md
      "import/newline-after-import": [
        Severity.WARN,
        { considerComments: true },
      ],

      // https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/no-duplicates.md
      "import/no-duplicates": Severity.WARN,

      // https://github.com/lydell/eslint-plugin-simple-import-sort
      "simple-import-sort/imports": Severity.WARN,
      "simple-import-sort/exports": Severity.WARN,
    },
  },

  {
    name: "dev-tools/typescript",
    files: ["**/*.ts?(x)"],

    extends: [
      // No rules, just base configurations.
      typescript.configs.base,
    ],

    // We use rules which require type information.
    //
    // https://typescript-eslint.io/getting-started/typed-linting
    languageOptions: {
      parserOptions: { projectService: true },
    },

    rules: {
      // https://typescript-eslint.io/rules/ban-ts-comment
      "@typescript-eslint/ban-ts-comment": Severity.WARN,

      // https://typescript-eslint.io/rules/method-signature-style
      // https://www.totaltypescript.com/method-shorthand-syntax-considered-harmful
      "@typescript-eslint/method-signature-style": [Severity.WARN, "property"],

      // https://typescript-eslint.io/rules/no-duplicate-enum-values
      "@typescript-eslint/no-duplicate-enum-values": Severity.WARN,

      // https://typescript-eslint.io/rules/no-duplicate-type-constituents
      "@typescript-eslint/no-duplicate-type-constituents": Severity.WARN,

      // https://typescript-eslint.io/rules/no-empty-object-type
      "@typescript-eslint/no-empty-object-type": [
        Severity.WARN,
        {
          // Allow declaration merging by exending types.
          //
          // Example:
          //   interface ProcessEnv extends zu.infer<typeof schema> {}
          allowInterfaces: "with-single-extends",
        },
      ],

      // https://typescript-eslint.io/rules/no-explicit-any
      "@typescript-eslint/no-explicit-any": Severity.WARN,

      // https://typescript-eslint.io/rules/no-extra-non-null-assertion
      "@typescript-eslint/no-extra-non-null-assertion": Severity.WARN,

      // https://typescript-eslint.io/rules/no-floating-promises
      "@typescript-eslint/no-floating-promises": Severity.WARN,

      // https://typescript-eslint.io/rules/no-for-in-array
      "@typescript-eslint/no-for-in-array": Severity.WARN,

      // https://typescript-eslint.io/rules/no-misused-new
      "@typescript-eslint/no-misused-new": Severity.WARN,

      // https://typescript-eslint.io/rules/no-misused-promises
      "@typescript-eslint/no-misused-promises": [
        Severity.WARN,
        {
          // Allow returning `Promise<void>` where `void` is expected.
          checksVoidReturn: false,
        },
      ],

      // https://typescript-eslint.io/rules/no-non-null-asserted-optional-chain
      "@typescript-eslint/no-non-null-asserted-optional-chain": Severity.WARN,

      // https://typescript-eslint.io/rules/no-redundant-type-constituents
      "@typescript-eslint/no-redundant-type-constituents": Severity.WARN,

      // https://typescript-eslint.io/rules/no-require-imports
      "@typescript-eslint/no-require-imports": Severity.WARN,

      // https://typescript-eslint.io/rules/no-unnecessary-type-assertion
      "@typescript-eslint/no-unnecessary-type-assertion": Severity.WARN,

      // https://typescript-eslint.io/rules/no-unsafe-declaration-merging
      "@typescript-eslint/no-unsafe-declaration-merging": Severity.WARN,

      // https://typescript-eslint.io/rules/no-unsafe-function-type
      "@typescript-eslint/no-unsafe-function-type": Severity.WARN,

      // https://typescript-eslint.io/rules/no-unsafe-unary-minus
      "@typescript-eslint/no-unsafe-unary-minus": Severity.WARN,

      // https://typescript-eslint.io/rules/no-unused-expressions
      "@typescript-eslint/no-unused-expressions": Severity.WARN,
      "no-unused-expressions": Severity.OFF,

      // https://typescript-eslint.io/rules/no-wrapper-object-types
      "@typescript-eslint/no-wrapper-object-types": Severity.WARN,

      // https://typescript-eslint.io/rules/prefer-as-const
      "@typescript-eslint/prefer-as-const": Severity.WARN,

      // https://typescript-eslint.io/rules/restrict-plus-operands
      "@typescript-eslint/restrict-plus-operands": Severity.WARN,

      // The rule doesn't support globals types and TypeScript already check
      // this.
      //
      // https://eslint.org/docs/latest/rules/no-undef
      "no-undef": Severity.OFF,

      // This is already checked by the TypeScript compiler.
      //
      // https://eslint.org/docs/latest/rules/no-redeclare
      "no-redeclare": Severity.OFF,
    },
  },

  {
    name: "dev-tools/typescript-type-import",
    files: ["**/*.ts?(x)"],

    rules: {
      // Use top level type import to improve readability.
      //
      // Invalid:
      //   import { SymbolA, type SymbolB, SymbolC } from 'module'
      //
      // Valid:
      //   import type { SymbolB } from 'module'
      //   import { SymbolA, SymbolC } from 'module'
      //
      // https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/consistent-type-specifier-style.md
      "import/consistent-type-specifier-style": [
        Severity.WARN,
        "prefer-top-level",
      ],

      // Enforce `import type` for imports only used in type positions.
      // Complements `verbatimModuleSyntax`, which only flags type symbols
      // (interfaces, aliases), not value symbols used exclusively via `typeof`.
      //
      // Invalid:
      //   import { loader } from './loader.server.js'
      //   export const meta: MetaFunction<typeof loader> = /* ... */
      //
      // Valid:
      //   import type { loader } from './loader.server.js'
      //   export const meta: MetaFunction<typeof loader> = /* ... */
      //
      // https://typescript-eslint.io/rules/consistent-type-imports
      "@typescript-eslint/consistent-type-imports": [
        Severity.WARN,
        {
          prefer: "type-imports",
          fixStyle: "separate-type-imports",
        },
      ],
    },
  },

  {
    name: "dev-tools/react-hooks",
    files: ["**/*.ts?(x)"],
    plugins: { "react-hooks": reactHooks },

    rules: {
      // https://www.npmjs.com/package/eslint-plugin-react-hooks/v/5.1.0
      "react-hooks/rules-of-hooks": Severity.ERROR,
      "react-hooks/exhaustive-deps": Severity.WARN,
    },
  },

  {
    name: "dev-tools/react",
    files: ["**/*.tsx"],
    plugins: { react },

    // Use `jsx-runtime` because we use React >17.
    //
    // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/README.md#flat-configs
    languageOptions: react.configs.flat["jsx-runtime"].languageOptions,

    settings: {
      react: { version: "detect" },
      formComponents: ["Form"],
      linkComponents: [
        { name: "Link", linkAttribute: "to" },
        { name: "NavLink", linkAttribute: "to" },
        { name: "BaseLink", linkAttribute: "to" },
      ],
    },

    rules: {
      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/display-name.md
      "react/display-name": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/jsx-key.md
      "react/jsx-key": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/jsx-no-comment-textnodes.md
      "react/jsx-no-comment-textnodes": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/jsx-no-duplicate-props.md
      "react/jsx-no-duplicate-props": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/jsx-no-target-blank.md
      "react/jsx-no-target-blank": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/no-danger-with-children.md
      "react/no-danger-with-children": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/no-deprecated.md
      "react/no-deprecated": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/no-string-refs.md
      "react/no-string-refs": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-react/blob/v7.37.2/docs/rules/no-unescaped-entities.md
      "react/no-unescaped-entities": [
        Severity.WARN,
        {
          // Allow `'` and `"` in JSX text node because we hard code text.
          forbid: [">", "}"],
        },
      ],
    },
  },

  {
    name: "dev-tools/jsx-a11y",
    files: ["**/*.tsx"],
    plugins: { "jsx-a11y": jsxA11y },

    rules: {
      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/alt-text.md
      "jsx-a11y/alt-text": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/anchor-has-content.md
      "jsx-a11y/anchor-has-content": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/anchor-is-valid.md
      "jsx-a11y/anchor-is-valid": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-activedescendant-has-tabindex.md
      "jsx-a11y/aria-activedescendant-has-tabindex": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-props.md
      "jsx-a11y/aria-props": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-proptypes.md
      "jsx-a11y/aria-proptypes": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-role.md
      "jsx-a11y/aria-role": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-unsupported-elements.md
      "jsx-a11y/aria-unsupported-elements": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/html-has-lang.md
      "jsx-a11y/html-has-lang": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/iframe-has-title.md
      "jsx-a11y/iframe-has-title": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/img-redundant-alt.md
      "jsx-a11y/img-redundant-alt": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/interactive-supports-focus.md
      "jsx-a11y/interactive-supports-focus": [
        Severity.WARN,
        {
          tabbable: [
            "button",
            "checkbox",
            "link",
            "searchbox",
            "spinbutton",
            "switch",
            "textbox",
          ],
        },
      ],

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/media-has-caption.md
      "jsx-a11y/media-has-caption": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-interactive-element-to-noninteractive-role.md
      "jsx-a11y/no-interactive-element-to-noninteractive-role": [
        Severity.WARN,
        {
          tr: ["none", "presentation"],
          canvas: ["img"],
        },
      ],

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-element-interactions.md
      "jsx-a11y/no-noninteractive-element-interactions": [
        Severity.WARN,
        {
          handlers: [
            "onClick",
            "onError",
            "onLoad",
            "onMouseDown",
            "onMouseUp",
            "onKeyPress",
            "onKeyDown",
            "onKeyUp",
          ],
          alert: ["onKeyUp", "onKeyDown", "onKeyPress"],
          body: ["onError", "onLoad"],
          dialog: ["onKeyUp", "onKeyDown", "onKeyPress"],
          iframe: ["onError", "onLoad"],
          img: ["onError", "onLoad"],
        },
      ],

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-element-to-interactive-role.md
      "jsx-a11y/no-noninteractive-element-to-interactive-role": [
        Severity.WARN,
        {
          ul: [
            "listbox",
            "menu",
            "menubar",
            "radiogroup",
            "tablist",
            "tree",
            "treegrid",
          ],
          ol: [
            "listbox",
            "menu",
            "menubar",
            "radiogroup",
            "tablist",
            "tree",
            "treegrid",
          ],
          li: [
            "menuitem",
            "menuitemradio",
            "menuitemcheckbox",
            "option",
            "row",
            "tab",
            "treeitem",
          ],
          table: ["grid"],
          td: ["gridcell"],
          fieldset: ["radiogroup", "presentation"],
        },
      ],

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-noninteractive-tabindex.md
      "jsx-a11y/no-noninteractive-tabindex": [
        Severity.WARN,
        {
          tags: [],
          roles: ["tabpanel"],
          allowExpressionValues: true,
        },
      ],

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-redundant-roles.md
      "jsx-a11y/no-redundant-roles": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/no-static-element-interactions.md
      "jsx-a11y/no-static-element-interactions": [
        Severity.WARN,
        {
          allowExpressionValues: true,
          handlers: [
            "onClick",
            "onMouseDown",
            "onMouseUp",
            "onKeyPress",
            "onKeyDown",
            "onKeyUp",
          ],
        },
      ],

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/role-has-required-aria-props.md
      "jsx-a11y/role-has-required-aria-props": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/role-supports-aria-props.md
      "jsx-a11y/role-supports-aria-props": Severity.WARN,

      // https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/tabindex-no-positive.md
      "jsx-a11y/tabindex-no-positive": Severity.WARN,
    },
  },
])
