name: ⚙️ Workspace - 🔬 Checks

on:
  pull_request:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🔬 Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🟧 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12
          cache: "pnpm"

      - name: 📥 Download deps
        run: pnpm install

      - name: 📦 Build libs
        run: pnpm --filter './libs/*...' build

      - name: 📦 Generate apps code
        run: pnpm --filter './apps/*' generate

      - name: 🔬 Lint
        run: pnpm lint
